In [3]:
import numpy as np

In [4]:
arr = [6,7,8,9]
arr

[6, 7, 8, 9]

In [5]:
print(type(arr))

<class 'list'>


In [7]:
a =np.array(arr) 
a

array([6, 7, 8, 9])

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(a.shape)

(4,)


In [10]:
print(a.dtype)

int32


In [11]:
print(a.ndim)

1


In [12]:
b  = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d =np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [19]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [20]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [21]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [23]:
d[1,  2:0]

array([], dtype=float64)

In [24]:
e = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [25]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [27]:
import pandas as pd

In [28]:
days = pd.Series(['Monday', 'Tuesday', "Wednesday"])
days

0       Monday
1      Tuesday
2    Wednesday
dtype: object

In [30]:
index = ['a', 'b', 'c']
day1 = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday'})
day1

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [31]:
days[0]

'Monday'

In [32]:
days[1: ]

1      Tuesday
2    Wednesday
dtype: object

In [33]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [42]:
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
        'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
        'Population': [10000, 8500, 35000,12000],
        'Age': [60, 70, 80, 75]}
df = pd.DataFrame(df_dict, index = [2, 4, 6, 8])

df_list = [['Gahna', 'Accra', 10000, 60],
          ['Kenya', 'Nairobi', 8500, 70],
          ['Nigeria', 'Abuja', 35000, 80],
          ['Togo', 'Lome', 12000, 75]]
df1 = pd.DataFrame(df_list, columns=['Country', 'Capital', 'Population', 'Age'], index=[2,4,6,8])

df1

Country  Capital  Population  Age
2    Gahna    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [43]:
df

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [44]:
df.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [45]:
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [49]:
df.at[6,'Country']

'Nigeria'

In [50]:
df.describe

<bound method NDFrame.describe of    Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75>

In [51]:
df['Population'].sum()

65500

In [52]:
df.mean()

Population    16375.00
Age              71.25
dtype: float64

In [53]:
df_dict2 = {'Name':['James', 'Yemen', 'Caro', np.nan],
           'Profession': ['Resseacher', 'Artist', 'Doctor', 'Writer'],
           'Experience': [12, np.nan, 10, 8],
           'Height': [np.nan, 175, 180, 150]}
Eche = pd.DataFrame(df_dict2)
Eche

Name  Profession  Experience  Height
0  James  Resseacher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [54]:
Eche.isnull()

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [55]:
Eche.dropna()

Name Profession  Experience  Height
2  Caro     Doctor        10.0   180.0

In [56]:
fuel_data_df = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')

In [57]:
fuel_data_df

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [58]:
fuel_data_df.mean()

utility_id_ferc1                1.186018e+02
report_year                     2.005806e+03
fuel_qty_burned                 2.622119e+06
fuel_mmbtu_per_unit             8.492111e+00
fuel_cost_per_unit_burned       2.086490e+02
fuel_cost_per_unit_delivered    9.175704e+02
fuel_cost_per_mmbtu             1.930435e+01
dtype: float64

In [60]:
fuel_data_df.describe

<bound method NDFrame.describe of                      record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant  

In [61]:
fuel_data_df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64